# Build Stage
FROM ringcentral/maven:3.8.2-jdk17 as build
COPY . .
RUN mvn clean package -DskipTests

# Package Stage
FROM eclipse-temurin:17-jdk-alpine
COPY --from=build target/insights-0.0.1-SNAPSHOT.jar /opt/insights.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/opt/insights.jar"]
